use_gpu: True
device: 0
early_stop:
  patience: 5
seed: 12345
federate:
  client_num: 3
  mode: standalone
data:
  root: data/
  type: mydata
  splits: [0.7,0,0.2]
  subsample: 0.05
  transform: [['ToTensor'], ['Normalize', {'mean': [0.9637], 'std': [0.1592]}]]
dataloader:
  batch_size: 10
model:
  type: mynet
  hidden: 2048
  out_channels: 62
train:
  local_update_steps: 1
  batch_or_epoch: epoch
  optimizer:
    lr: 0.01
    weight_decay: 0.0
grad:
  grad_clip: 5.0
criterion:
  type: CrossEntropyLoss
trainer:
  type: mytrainer
eval:
  freq: 10
  metrics: ['acc', 'correct']